[project]
name = "block-based-double-decoder"
version = "0.1.0"
description = "Training and evaluation code for the block-based double decoder project."
requires-python = "==3.11.*"
dependencies = [
    "blobfile==3.0.0",
    "datasets==4.0.0",
    "flash-attn>=2.8.3,<3",
    "hf-transfer==0.1.9",
    "huggingface-hub==0.33.4",
    "matplotlib==3.10.1",
    "numpy==2.3.1",
    "omegaconf==2.3.0",
    "pandas==2.3.1",
    "pyarrow==20.0.0",
    "sentencepiece==0.2.0",
    "tokenizers==0.21.2",
    "torchao==0.11.0",
    "torchdata==0.11.0",
    "torchtune==0.6.1",
    "tqdm==4.67.1",
    "transformers==4.53.2",
    "wandb==0.21.0",
]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
conflicts = [
    [{ extra = "cu118" }, { extra = "cu126" }],
    [{ extra = "cu118" }, { extra = "cu128" }],
    [{ extra = "cu126" }, { extra = "cu128" }],
]

[project.optional-dependencies]
cu118 = [
    "torch<=2.7.1",
]
cu126 = [
    "torch>=2.9.0",
]
cu128 = [
    "torch>=2.9.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu118", extra = "cu118" },
    { index = "pytorch-cu126", extra = "cu126" },
    { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]